<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <AssemblyName>Pulse.Authorization.Infrastructure</AssemblyName>
	  <RootNamespace>Pulse.Authorization.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value> **/Constants/GlobalConstants.cs</Value>
    </SonarQubeSetting>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
    <PackageReference Include="Polly" Version="8.4.1" />
    <PackageReference Include="Pulse.Back.Events" Version="1.73.2" />
    <PackageReference Include="Pulse.ExceptionMiddleware" Version="2.73.24" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Authorization.Core\Authorization.Core.csproj" />
  </ItemGroup>

</Project>
      