// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

using Entities = Authorization.Infrastructure.Entities;

namespace Authorization.Infrastructure.Context;

public partial class AuthorizationContext : DbContext
{
    public AuthorizationContext(DbContextOptions<AuthorizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Entities.AccountEntity> AccountEntity { get; set; }

    public virtual DbSet<Entities.AccountResource> AccountResource { get; set; }

    public virtual DbSet<Entities.Action> Action { get; set; }

    public virtual DbSet<Entities.Authorization> Authorization { get; set; }

    public virtual DbSet<Entities.ContactEntity> ContactEntity { get; set; }

    public virtual DbSet<Entities.Personna> Personna { get; set; }

    public virtual DbSet<Entities.Resource> Resource { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entities.AccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("C_TAccount_PK");

            entity.ToTable("Account", "account");

            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Entities.AccountResource>(entity =>
        {
            entity.HasKey(e => new { e.AccountId, e.ResourceId });

            entity.ToTable("AccountResource", "auth");
        });

        modelBuilder.Entity<Entities.Action>(entity =>
        {
            entity.ToTable("Action", "auth");

            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Entities.Authorization>(entity =>
        {
            entity.HasKey(e => new { e.ContactId, e.AccountId, e.ActionId });

            entity.ToTable("Authorization", "auth");

            entity.HasOne(d => d.Account).WithMany(p => p.Authorization)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Authorization_Account");

            entity.HasOne(d => d.Action).WithMany(p => p.Authorization)
                .HasForeignKey(d => d.ActionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Authorization_Action");

            entity.HasOne(d => d.Contact).WithMany(p => p.Authorization)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Authorization_Contact");
        });

        modelBuilder.Entity<Entities.ContactEntity>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("C_TContact_PK");

            entity.ToTable("Contact", "actor");

            entity.Property(e => e.ContactEmail)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PersonnaName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Entities.Personna>(entity =>
        {
            entity.ToTable("Personna", "auth");

            entity.Property(e => e.PersonnaId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasMany(d => d.Action).WithMany(p => p.Personna)
                .UsingEntity<Dictionary<string, object>>(
                    "PersonnaAction",
                    r => r.HasOne<Entities.Action>().WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PersonnaAction_Action"),
                    l => l.HasOne<Entities.Personna>().WithMany()
                        .HasForeignKey("PersonnaId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PersonnaAction_Personna"),
                    j =>
                    {
                        j.HasKey("PersonnaId", "ActionId");
                        j.ToTable("PersonnaAction", "auth");
                    });
        });

        modelBuilder.Entity<Entities.Resource>(entity =>
        {
            entity.HasKey(e => e.ResourceId).HasName("PK_Ressource");

            entity.ToTable("Resource", "auth");

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Url)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Permission_Premission");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
