// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pulse.Authorization.Infrastructure.Entities;

namespace Pulse.Authorization.Infrastructure.Context;

public partial class AuthorizationContext : DbContext
{
    public AuthorizationContext(DbContextOptions<AuthorizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountEntity> AccountEntity { get; set; }

    public virtual DbSet<AuthorizationEntity> AuthorizationEntity { get; set; }

    public virtual DbSet<ContactAuthorization> ContactAuthorization { get; set; }

    public virtual DbSet<ContactEntity> ContactEntity { get; set; }

    public virtual DbSet<Persona> Persona { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("C_TAccount_PK");

            entity.ToTable("Account", "account");

            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasMany(d => d.Authorization).WithMany(p => p.Account)
                .UsingEntity<Dictionary<string, object>>(
                    "AccountAuthorization",
                    r => r.HasOne<AuthorizationEntity>().WithMany()
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AccountAuthorization_Authorization"),
                    l => l.HasOne<AccountEntity>().WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AccountAuthorization_Account"),
                    j =>
                    {
                        j.HasKey("AccountId", "AuthorizationId");
                        j.ToTable("AccountAuthorization", "auth");
                    });
        });

        modelBuilder.Entity<AuthorizationEntity>(entity =>
        {
            entity.HasKey(e => e.AuthorizationId);

            entity.ToTable("Authorization", "auth");

            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ContactAuthorization>(entity =>
        {
            entity.HasKey(e => new { e.ContactId, e.AccountId, e.AuthorizationId });

            entity.ToTable("ContactAuthorization", "auth");

            entity.Property(e => e.CreationDate).HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.ContactAuthorization)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContactAuthorization_Account");

            entity.HasOne(d => d.Authorization).WithMany(p => p.ContactAuthorization)
                .HasForeignKey(d => d.AuthorizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContactAuthorization_Authorization");

            entity.HasOne(d => d.Contact).WithMany(p => p.ContactAuthorization)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContactAuthorization_Contact");
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("C_TContact_PK");

            entity.ToTable("Contact", "actor");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PersonaName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.ToTable("Persona", "auth");

            entity.Property(e => e.PersonaId).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasMany(d => d.Authorization).WithMany(p => p.Persona)
                .UsingEntity<Dictionary<string, object>>(
                    "PersonaAuthorization",
                    r => r.HasOne<AuthorizationEntity>().WithMany()
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PersonaAuthorization_Authorization"),
                    l => l.HasOne<Persona>().WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PersonaAuthorization_Personna"),
                    j =>
                    {
                        j.HasKey("PersonaId", "AuthorizationId");
                        j.ToTable("PersonaAuthorization", "auth");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}