// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pulse.Authorization.Infrastructure.Entities;

namespace Pulse.Authorization.Infrastructure.Context;

public partial class AuthorizationContext : DbContext
{
    public AuthorizationContext(DbContextOptions<AuthorizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountAuthorization> AccountAuthorization { get; set; }

    public virtual DbSet<AccountEntity> AccountEntity { get; set; }

    public virtual DbSet<AuthorizationEntity> AuthorizationEntity { get; set; }

    public virtual DbSet<ContactAuthorization> ContactAuthorization { get; set; }

    public virtual DbSet<ContactEntity> ContactEntity { get; set; }

    public virtual DbSet<Persona> Persona { get; set; }

    public virtual DbSet<PersonaAuthorization> PersonaAuthorization { get; set; }

    public virtual DbSet<ResourceEntity> ResourceEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountAuthorization>(entity =>
        {
            entity.HasKey(e => new { e.AccountId, e.AuthorizationId });

            entity.ToTable("AccountAuthorization", "auth");

            entity.HasOne(d => d.Account).WithMany(p => p.AccountAuthorization)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountAuthorization_Account");

            entity.HasOne(d => d.Authorization).WithMany(p => p.AccountAuthorization)
                .HasForeignKey(d => d.AuthorizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountAuthorization_Authorization");
        });

        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("C_TAccount_PK");

            entity.ToTable("Account", "account");

            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AuthorizationEntity>(entity =>
        {
            entity.HasKey(e => e.AuthorizationId);

            entity.ToTable("Authorization", "auth");

            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ContactAuthorization>(entity =>
        {
            entity.HasKey(e => new { e.ContactId, e.AccountId, e.AuthorizationId });

            entity.ToTable("ContactAuthorization", "auth");

            entity.Property(e => e.CreationDate).HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.ContactAuthorization)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContactAuthorization_Account");

            entity.HasOne(d => d.Authorization).WithMany(p => p.ContactAuthorization)
                .HasForeignKey(d => d.AuthorizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContactAuthorization_Authorization");

            entity.HasOne(d => d.Contact).WithMany(p => p.ContactAuthorization)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContactAuthorization_Contact");
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("C_TContact_PK");

            entity.ToTable("Contact", "actor");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PersonaName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.ToTable("Persona", "auth");

            entity.Property(e => e.PersonaId).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PersonaAuthorization>(entity =>
        {
            entity.HasKey(e => new { e.PersonaId, e.AuthorizationId });

            entity.ToTable("PersonaAuthorization", "auth");

            entity.HasOne(d => d.Authorization).WithMany(p => p.PersonaAuthorization)
                .HasForeignKey(d => d.AuthorizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonaAuthorization_Authorization");

            entity.HasOne(d => d.Persona).WithMany(p => p.PersonaAuthorization)
                .HasForeignKey(d => d.PersonaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonaAuthorization_Personna");
        });

        modelBuilder.Entity<ResourceEntity>(entity =>
        {
            entity.HasKey(e => e.ResourceId).HasName("PK_Ressource");

            entity.ToTable("Resource", "auth");

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Authorization_Authorization");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}