trigger: none
pool:
  vmImage: windows-latest

parameters:
- name: devIndex
  displayName: 'Index de l environnement cible (seulement pour un déploiement sur env de DEV)'
  type: number
  default: 0
- name: deployType
  displayName: "Technical parameter : don t modify it !"
  type: string
  default: 'standard'
  values:
    - standard
    - onlyDev

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v3.0'

extends:
  template: pipelines/templates/platform.back.sql.yaml@Pulse
  parameters:
    devIndex: ${{ parameters.devIndex }}
    deployType: ${{ parameters.deployType }}
    sonarExclusions: '**/Authorization.Database/ScriptRec/**, **/Authorization.Database/postDeployment/**'
    domain: aut
    resource:
      id: '01'
      name: 'authorization'
      path: 01_authorization\src\Authorization.Database\Authorization.Database.sqlproj
    dotnetcore: 8.x