trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: false
- name: deployToItg
  displayName: 'Déployer sur ITG'
  type: boolean
  default: true
- name: deployToRec
  displayName: 'Déployer sur REC'
  type: boolean
  default: true
- name: deployToPrd
  displayName: 'Déployer sur PROD'
  type: boolean
  default: true


resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/delivery/back.yaml@Pulse
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    deployToItg: ${{ parameters.deployToItg }}
    deployToRec: ${{ parameters.deployToRec }}
    deployToPrd: ${{ parameters.deployToPrd }}
    srcPath: 01_authorization/src/Authorization.API/Authorization.API.csproj
    testsPath: 01_authorization/tests/**/*Tests.csproj
    sonarExclusions: '**/Authorization.Database/Mocks.dev/**,**/Authorization.Database/Scripts/**,**/Authorization.Database/postDeployment/**,**/tests/**'
    domain: aut
    name: authorization
    appType: webApp
    id: '01'