IF (SELECT count(*) FROM [auth].[Authorization]) = 0
BEGIN
INSERT INTO [auth].[Authorization] (
	[Name], [Description], [Code], [Label], [Category], [Configurable], [View], [ProductCode], [Type], [TargetAccountType])
	VALUES
	('Super Admin', '', 'CLADMI001', 'Droit Super Admin client', 'CLTGESTION', '0', 'Global', NULL, 'customer', 'Client'),
	('View User', '', 'CLUSER001', 'Consulter les utilisateurs', 'CLTGESTION', '1', 'Partial', NULL, 'customer', 'All'),
	('Add User', '', 'CLUSER002', 'Ajouter un utilisateur', 'CLTGESTION', '1', 'Partial',NULL, 'customer', 'All'),
	('Delete User', '', 'CLUSER003', 'Supprimer un utilisateur', 'CLTGESTION', '1', 'Partial',NULL, 'customer', 'All'),
	('Update right', '', 'CLUSER004', 'Gérer les droits utilisateurs', 'CLTGESTION', '1', 'Both', NULL, 'customer', 'All'),
	('View offers', '', 'CLOFF001', 'Accéder aux offres souscrites', 'CLTGESTION', '1', 'Partial', NULL, 'customer', 'Client'),
	('View informations', '', 'CLINFO001', 'Accéder aux informations d''entreprise', 'CLTGESTION', '1', 'Both', NULL, 'customer', 'All'),
	('View Invoice', '', 'CLINVO001', 'Accéder aux factures Rydge Conseil', 'CLTGESTION', '1', 'Partial', NULL, 'customer', 'Client'),
	('View GED GS', '', 'CLGED0001', 'Accéder à la GED Gestion sociale', 'CLTGEDGS', '1', 'Partial', 'gedgs', 'customer', 'Client'),
	('View GED ESC', '', 'CLGED0002', 'Accéder à la GED Comptable', 'CLTGEDESC', '1', 'Partial', 'gedesc', 'customer', 'Client'),
	('Access Silae', '', 'CLSILA001', 'Accéder à l''outil Silae', 'CLTGS', '1', 'Partial', 'silaeaccess', 'customer', 'Client'),
	('View EVP', '', 'CLEVP001', 'Accéder aux EVP', 'CLTGS', '0', 'Partial', 'EVP', 'customer', 'Client'),
	('View hiring', '', 'CLEMB001', 'Accéder à l''embauche salariée', 'CLTGS', '0', 'Partial', 'Hiring', 'customer', 'Client'),
	('Access MEG', '', 'CLMEG001', 'Accéder à l''outil MEG', 'CLTESC', '1', 'Partial', 'megaccess', 'customer', 'Client'),
	('Access Pennylane', '', 'CLPEN001', 'Accéder à l''outil Pennylane', 'CLTESC', '1', 'Partial','pennylaneaccess', 'customer', 'Client'),
	('View bi financial', '', 'CLRAPP001', 'Accéder aux rapports BI Financier', 'CLTPILOTAGE', '1', 'Partial',NULL, 'customer', 'Client'),
	('View bi HR', '', 'CLRAPP002', 'Accéder aux rapports BI RH', 'CLTPILOTAGE', '0', 'Partial', NULL, 'customer', 'Client'),
	('View kpi', '', 'CLKPI0001', 'Accéder aux indicateurs', 'CLTPILOTAGE', '0', 'Partial', NULL, 'customer', 'Client'),
	('View bank', '', 'CLBANK001', 'Accéder aux données bancaires', 'CLTPILOTAGE', '0', 'Partial', NULL, 'customer', 'Client'),
	('View collabs', '', 'COADMI001', 'Accéder à l''onglet collaborateurs', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Delete collab', '', 'COADMI002', 'Supprimer un collaborateur', 'COLADMIN', '1', 'Both', NULL, 'collaborator', 'Client'),
	('Update right collab', '', 'COADMI003', 'Gérer les droits des collaborateurs', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('View account administration', '', 'COADMI004', 'Gérer les dossiers', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Update right account', '', 'COADMI005', 'Gestion des droits sur dossier', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Add User', '', 'COADMI006', 'Ajouter un utilisateur', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Remove client user from an account', '', 'COUSER003', 'Retirer utilisateur client d''un dossier', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Create JDD', '', 'COADMI007', 'Créer des jeux de données', 'COLADMIN', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Deploy subscription', '', 'COOFF001', 'Activer une offre', 'COLOFFRE', '1', 'Both', NULL, 'collaborator', 'Client'),
	('Activate subsciption', '', 'COOFF002', 'Onglet des demandes MOD', 'COLOFFRE', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Access AI Mode', '', 'COAIOFFER', 'Accéder au mode IA du catalogue des offres', 'COLOFFRE', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Report administration', '', 'CORAP001', 'Administrer les rapports BI', 'COLRAPPORT', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Add report', '', 'CORAP002', 'Déposer un rapport BI', 'COLRAPPORT', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Delete report', '', 'CORAP003', 'Supprimer un rapport BI', 'COLRAPPORT', '1', 'Global', NULL, 'collaborator', 'Client'),
	('View delegation', '', 'COGES001', 'Historique des délégations', 'COLGESTION', '1', 'Both', NULL, 'collaborator', 'Client'),
	('View Calendar', '', 'COCAL001', 'Accéder au calendrier', 'COLGESTION', '1', 'Header', NULL, 'collaborator', 'Client'),
	('View mandate', '', 'COMAND001', 'Onglet Mandat', 'COLPROD', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Mirror GED GS', '', 'COGED0001', 'Accéder à la GED Gestion sociale', 'COLPROD', '1', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror GED ESC', '', 'COGED0002', 'Accéder à la GED Comptable', 'COLPROD', '1', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror users customer', '', 'COUSER001', 'Accéder à l''onglet utilisateurs', 'COLMIRROIR', '1', 'Both', NULL, 'collaborator', 'Client'),
	('Mirror users collab', '', 'COUSER002', 'Accéder à l''onglet collaborateurs', 'COLMIRROIR', '1', 'Both', NULL, 'collaborator', 'Client'),
	('Mirror offer', '', 'COOFF003', 'Accéder à l''onglet offre', 'COLMIRROIR', '1', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror informations', '', 'COINFO001', 'Accéder à l''onglet informations', 'COLMIRROIR', '1', 'Both', NULL, 'collaborator', 'Client'),
	('Update informations', '', 'COINFO002', 'MAJ la fiche entreprise (onglet information)', 'COLGESTION', '1', 'Both', NULL, 'collaborator', 'Client'),
	('Mirror invoice', '', 'COINVO001', 'Accéder aux factures Rydge Conseil', 'COLMIRROIR', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Mirror EVP', '', 'COEVPO01', 'Accéder aux EVP', 'COLMIRROIR', '0', 'Partial', 'EVP', 'collaborator', 'Client'),
	('Mirror hiring', '', 'COEMB001', 'Accéder à l''embauche salariée', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror launcher', '', 'COLANC001', 'Accéder aux lançeurs d''outils externes', 'COLMIRROIR', '1', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror report', '', 'CORAPP001', 'Accéder aux rapports BI ', 'COLMIRROIR', '1', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror kpi', '', 'COKPI0001', 'Accéder aux indicateurs', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator', 'Client'),
	('Mirror bank', '', 'COBANK001', 'Accéder aux données bancaires', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator', 'Client'),
	('Access Silae collab', '', 'COSILA001', 'Accéder au lanceur silae', 'COLGESTION', '1', 'Global', NULL, 'collaborator', 'Client'),
	('Access Pennylane collab', '', 'COPEN001', 'Accéder au lanceur pennylane', 'COLGESTION', '1', 'Both', 'pennylaneaccess', 'collaborator', 'Client'),
	('Access Rydge Conseil', '', 'CLGEDPEN01', 'Accéder à l''espace documentaire Rydge Conseil', 'CLTGEDESC', '1', 'Partial', 'pennylaneaccess', 'customer', 'Client'),
	('Manage booking page', '', 'CORDV001', 'Gérer ma page de rendez-vous avec booking', 'COLGESTION', '1', 'Global', NULL, 'collaborator', 'Client'),
	-- Prospect permissions
	('View Prospect Folders', '', 'COPROS001', 'Voir les dossiers prospects', 'COLPROS', '0', 'Global', NULL, 'collaborator', 'Prospect'),
	('Access Beneficial Owners Section', '', 'CLPCONF001', 'Accéder à la section Bénéficiaires Effectifs', 'CLTPCONF', '1', 'Partial', NULL, 'customer', 'Prospect'),
	('Access Documents Section', '', 'CLPCONF002', 'Accéder à la section Documents', 'CLTPCONF', '1', 'Partial', NULL, 'customer', 'Prospect'),
	('Access Commercial Proposal Section', '', 'CLPCONF004', 'Accéder à la section Proposition commerciale', 'CLTPCONF', '1', 'Partial', NULL, 'customer', 'Prospect'),
	('Access Payment Method Section', '', 'CLPCONF005', 'Accéder à la section Moyen de paiement', 'CLTPCONF', '1', 'Partial', NULL, 'customer', 'Prospect'),
	('Access Mission Letter Section', '', 'CLPCONF006', 'Accéder à la section Lettre de mission', 'CLTPCONF', '1', 'Partial', NULL, 'customer', 'Prospect'),
	('Access Documents Folder', '', 'CLPDOCP001', 'Accéder au dossier Documents', 'CLTPDOCP', '1', 'Partial', NULL, 'customer', 'Prospect'),
	-- Finthesis permissions
	('Add Finthesis report', '', 'COFIN001', 'Déposer un rapport Finthesis', 'COLRAPPORT', '1', 'Partial', 'Finthesis', 'collaborator', 'Client'),
	('Mirror Finthesis reports', '', 'COFINM001', 'Accéder aux rapports Finthesis', 'COLMIRROIR', '1', 'Partial', 'Finthesis', 'collaborator', 'Client'),
	('View Finthesis reports', '', 'CLFIN001', 'Accéder aux rapports Finthesis', 'CLTPILOTAGE', '1', 'Partial', 'Finthesis', 'customer', 'Client')
END
