IF (SELECT count(*) FROM [auth].[Authorization]) = 0
BEGIN
SET IDENTITY_INSERT [auth].[Authorization] ON; 
	INSERT INTO [auth].[Authorization] ([Name], [Description], [Code], [Label], [Category], [Configurable]) VALUES 
		('Super Admin', '', 'CLADMI001', 'Droit Super Admin client', 'CltGESTION', '0'),
		('View User', '', 'CLUSER001', 'Consulter les utilisateurs', 'CltGESTION', '1'),
		('Add User', '', 'CLUSER002', 'Ajouter un utilisateur', 'CltGESTION', '1'),
		('Delete User', '', 'CLUSER003', 'Supprimer un utilisateur', 'CltGESTION', '1'),
		('Update right', '', 'CLUSER004', 'Gérer les droits utilisateurs', 'CltGESTION', '1'),
		('View offers', '', 'CLOFF001', 'Accéder aux offres souscrites', 'CltGESTION', '1'),
		('View informations', '', 'CLINFO001', 'Accéder aux informations d''entreprise', 'CltGESTION', '1'),
		('View Invoice', '', 'CLINVO001', 'Accéder aux factures Pulse', 'CltGESTION', '0'),
		('View GED GS', '', 'CLGED0001', 'Accéder à la GED Gestion sociale', 'CltGED GS', '1'),
		('View GED ESC', '', 'CLGED0002', 'Accéder à la GED Comptable', 'CltGED ESC', '1'),
		('Access Silae', '', 'CLSILA001', 'Accéder à l''outil Silae', 'CltGS', '1'),
		('View EVP', '', 'CLEVPO01', 'Accéder aux EVP', 'CltGS', '0'),
		('View hiring', '', 'CLEMB001', 'Accéder à l''embauche salariée', 'CltGS', '0'),
		('Access MEG', '', 'CLMEG001', 'Accéder à l''outil MEG', 'CltESC', '1'),
		('Access Pennylane', '', 'CLPEN001', 'Accéder à l''outil Pennylane', 'CltESC', '1'),
		('View bi financial', '', 'CLRAPP001', 'Accéder aux rapports BI Financier', 'CltPILOTAGE', '1'),
		('View bi HR', '', 'CLRAPP002', 'Accéder aux rapports BI RH', 'CltPILOTAGE', '0'),
		('View kpi', '', 'CLKPI0001', 'Accéder aux indicateurs', 'CltPILOTAGE', '0'),
		('View bank', '', 'CLBank001', 'Accéder aux données bancaires', 'CltPILOTAGE', '0'),
		('Administration Pulse', '', 'COADMI001', 'Administration des utilisateurs de la plateforme', 'ColADMIN', '1'),
		('View mandate', '', 'COMAND001', 'Onglet Mandat', 'ColESC', '1'),
		('Deploy subscription', '', 'COOFF001', 'Déployer une offre', 'ColOFFRE', '1'),
		('Activate subsciption', '', 'COOFF002', 'Onglet des demandes MOD', 'ColOFFRE', '1'),
		('Add report', '', 'CORAP001', 'Déposer un rapport BI', 'ColRAPPORT', '1'),
		('View delegation', '', 'COGES001', 'Historique des délégations', 'ColGESTION', '1'),
		('View Calendar', '', 'COCAL001', 'Accéder au calendrier', 'ColGESTION', '1'),
		('Mirror users customer', '', 'COUSER001', 'Accéder à l''onglet utilisateurs', 'ColMIRROIR', '1'),
		('Mirror users collab', '', 'COUSER002', 'Accéder à l''onglet collaborateurs', 'ColMIRROIR', '1'),
		('Mirror offer', '', 'COOFF003', 'Accéder à l''onglet offre', 'ColMIRROIR', '1'),
		('Mirror informations', '', 'COINFO001', 'Accéder à l''onglet informations', 'ColMIRROIR', '1'),
		('Mirror invoice', '', 'COINVO001', 'Accéder aux factures Pulse', 'ColMIRROIR', '0'),
		('Mirror GED GS', '', 'COGED0001', 'Accéder à la GED Gestion sociale', 'ColMIRROIR', '1'),
		('Mirror GED ESC', '', 'COGED0002', 'Accéder à la GED Comptable', 'ColMIRROIR', '1'),
		('Mirror Silae', '', 'COSILA001', 'Accéder au lanceur silae', 'ColMIRROIR', '1'),
		('Mirror EVP', '', 'COEVPO01', 'Accéder aux EVP', 'ColMIRROIR', '0'),
		('Mirror hiring', '', 'COEMB001', 'Accéder à l''embauche salariée', 'ColMIRROIR', '0'),
		('Mirror launcher', '', 'COLANC001', 'Accéder aux lanceurs d''outils externes', 'ColMIRROIR', '1'),
		('Mirror report', '', 'CORAPP001', 'Accéder aux rapports BI ', 'ColMIRROIR', '1'),
		('Mirror kpi', '', 'COKPI0001', 'Accéder aux indicateurs', 'ColMIRROIR', '0'),
		('Mirror bank', '', 'COBank001', 'Accéder aux données bancaires', 'ColMIRROIR', '0')
SET IDENTITY_INSERT [auth].[Authorization] OFF;
END