IF (SELECT count(*) FROM [auth].[Authorization]) = 0
BEGIN
INSERT INTO auth.[Authorization] (
	Name, Description, Code, Label, Category, Configurable, [View], [ProductCode], [Type])
	VALUES
	('Super Admin', '', 'CLADMI001', 'Droit Super Admin client', 'CLTGESTION', '0', 'Global', NULL, 'customer'),
	('View User', '', 'CLUSER001', 'Consulter les utilisateurs', 'CLTGESTION', '1', 'Both', NULL, 'customer'),
	('Add User', '', 'CLUSER002', 'Ajouter un utilisateur', 'CLTGESTION', '1', 'Partial',NULL, 'customer'),
	('Delete User', '', 'CLUSER003', 'Supprimer un utilisateur', 'CLTGESTION', '1', 'Partial',NULL, 'customer'),
	('Update right', '', 'CLUSER004', 'Gérer les droits utilisateurs', 'CLTGESTION', '1', 'Both', NULL, 'customer'),
	('View offers', '', 'CLOFF001', 'Accéder aux offres souscrites', 'CLTGESTION', '1', 'Partial', NULL, 'customer'),
	('View informations', '', 'CLINFO001', 'Accéder aux informations d''entreprise', 'CLTGESTION', '1', 'Both', NULL, 'customer'),
	('View Invoice', '', 'CLINVO001', 'Accéder aux factures Pulse', 'CLTGESTION', '0', 'Partial', NULL, 'customer'),
	('View GED GS', '', 'CLGED0001', 'Accéder à la GED Gestion sociale', 'CLTGEDGS', '1', 'Partial', 'gedgs', 'customer'),
	('View GED ESC', '', 'CLGED0002', 'Accéder à la GED Comptable', 'CLTGEDESC', '1', 'Partial', 'gedesc', 'customer'),
	('Access Silae', '', 'CLSILA001', 'Accéder à l''outil Silae', 'CLTGS', '1', 'Partial', 'silaeaccess', 'customer'),
	('View EVP', '', 'CLEVP001', 'Accéder aux EVP', 'CLTGS', '0', 'Partial', 'EVP', 'customer'),
	('View hiring', '', 'CLEMB001', 'Accéder à l''embauche salariée', 'CLTGS', '0', 'Partial', 'Hiring', 'customer'),
	('Access MEG', '', 'CLMEG001', 'Accéder à l''outil MEG', 'CLTESC', '1', 'Partial', 'megaccess', 'customer'),
	('Access Pennylane', '', 'CLPEN001', 'Accéder à l''outil Pennylane', 'CLTESC', '1', 'Partial','pennylaneaccess', 'customer'),
	('View bi financial', '', 'CLRAPP001', 'Accéder aux rapports BI Financier', 'CLTPILOTAGE', '1', 'Partial',NULL, 'customer'),
	('View bi HR', '', 'CLRAPP002', 'Accéder aux rapports BI RH', 'CLTPILOTAGE', '0', 'Partial', NULL, 'customer'),
	('View kpi', '', 'CLKPI0001', 'Accéder aux indicateurs', 'CLTPILOTAGE', '0', 'Partial', NULL, 'customer'),
	('View bank', '', 'CLBANK001', 'Accéder aux données bancaires', 'CLTPILOTAGE', '0', 'Partial', NULL, 'customer'),
	('View collabs', '', 'COADMI001', 'Accéder à l''onglet collaborateurs', 'COLADMIN', '1', 'Global', NULL, 'collaborator'),
	('Delete collab', '', 'COADMI002', 'Supprimer un collaborateur', 'COLADMIN', '1', 'Both', NULL, 'collaborator'),
	('Update right collab', '', 'COADMI003', 'Gérer les droits des collaborateurs', 'COLADMIN', '1', 'Global', NULL, 'collaborator'),
	('View account administration', '', 'COADMI004', 'Gérer les dossiers', 'COLADMIN', '1', 'Global', NULL, 'collaborator'),
	('Update right account', '', 'COADMI005', 'Gestion des droits sur dossier', 'COLADMIN', '1', 'Global', NULL, 'collaborator'),
	('Remove client user from an account', '', 'COUSER003', 'Retirer utilisateur client d''un dossier', 'COLADMIN', '1', 'Global', NULL, 'collaborator'),
	('Create JDD', '', 'COADMI007', 'Créer des jeux de données', 'COLADMIN', '1', 'Global', NULL, 'collaborator'),
	('Deploy subscription', '', 'COOFF001', 'Activer une offre', 'COLOFFRE', '1', 'Both', NULL, 'collaborator'),
	('Activate subsciption', '', 'COOFF002', 'Onglet des demandes MOD', 'COLOFFRE', '1', 'Global', NULL, 'collaborator'),
	('Add report', '', 'CORAP001', 'Déposer un rapport BI', 'COLRAPPORT', '1', 'Global', NULL, 'collaborator'),
	('View delegation', '', 'COGES001', 'Historique des délégations', 'COLGESTION', '1', 'Both', NULL, 'collaborator'),
	('View Calendar', '', 'COCAL001', 'Accéder au calendrier', 'COLGESTION', '1', 'Header', NULL, 'collaborator'),
	('View mandate', '', 'COMAND001', 'Onglet Mandat', 'COLPROD', '1', 'Global', NULL, 'collaborator'),
	('Mirror GED GS', '', 'COGED0001', 'Accéder à la GED Gestion sociale', 'COLPROD', '1', 'Partial', NULL, 'collaborator'),
	('Mirror GED ESC', '', 'COGED0002', 'Accéder à la GED Comptable', 'COLPROD', '1', 'Partial', NULL, 'collaborator'),
	('Mirror users customer', '', 'COUSER001', 'Accéder à l''onglet utilisateurs', 'COLMIRROIR', '1', 'Both', NULL, 'collaborator'),
	('Mirror users collab', '', 'COUSER002', 'Accéder à l''onglet collaborateurs', 'COLMIRROIR', '1', 'Both', NULL, 'collaborator'),
	('Mirror offer', '', 'COOFF003', 'Accéder à l''onglet offre', 'COLMIRROIR', '1', 'Partial', NULL, 'collaborator'),
	('Mirror informations', '', 'COINFO001', 'Accéder à l''onglet informations', 'COLMIRROIR', '1', 'Both', NULL, 'collaborator'),
	('Update informations', '', 'COINFO002', 'MAJ la fiche entreprise (onglet information)', 'COLGESTION', '1', 'Both', NULL, 'collaborator'),
	('Mirror invoice', '', 'COINVO001', 'Accéder aux factures Pulse', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator'),
	('Mirror EVP', '', 'COEVPO01', 'Accéder aux EVP', 'COLMIRROIR', '0', 'Partial', 'EVP', 'collaborator'),
	('Mirror hiring', '', 'COEMB001', 'Accéder à l''embauche salariée', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator'),
	('Mirror launcher', '', 'COLANC001', 'Accéder aux lançeurs d''outils externes', 'COLMIRROIR', '1', 'Partial', NULL, 'collaborator'),
	('Mirror report', '', 'CORAPP001', 'Accéder aux rapports BI ', 'COLMIRROIR', '1', 'Partial', NULL, 'collaborator'),
	('Mirror kpi', '', 'COKPI0001', 'Accéder aux indicateurs', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator'),
	('Mirror bank', '', 'COBANK001', 'Accéder aux données bancaires', 'COLMIRROIR', '0', 'Partial', NULL, 'collaborator'),
	('Access Silae collab', '', 'COSILA001', 'Accéder au lanceur silae', 'COLGESTION', '1', 'Global', NULL, 'collaborator')
	('Access Pennylane collab', '', 'COPEN001', 'Accéder au lanceur pennylane', 'COLGESTION', '1', 'Global', NULL, 'collaborator')
END
