// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class AccountEntity
{
    public int AccountId { get; set; }

    public Guid AccountGlobalUniqueId { get; set; }

    public string AccountNumber { get; set; }

    public string LegalName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<AuthorizationEntity> AuthorizationEntity { get; set; } = new List<AuthorizationEntity>();
}
