// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class AccountAuthorizationEntity
{
    public int AccountId { get; set; }

    public int AuthorizationId { get; set; }

    public bool? Enabled { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual AuthorizationEntity Authorization { get; set; }
}