// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class AccountResourceEntity
{
    public int AccountId { get; set; }

    public int ResourceId { get; set; }
}
