// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authorization.Infrastructure.Entities;

public partial class Action
{
    public int ActionId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Code { get; set; }

    public string Category { get; set; }

    public virtual ICollection<Authorization> Authorization { get; set; } = new List<Authorization>();

    public virtual ICollection<Personna> Personna { get; set; } = new List<Personna>();
}