// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class AuthorizationEntity
{
    public int AuthorizationId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public string Category { get; set; }

    public bool? Configurable { get; set; }

    public virtual ICollection<AccountAuthorizationEntity> AccountAuthorizationEntity { get; set; } = new List<AccountAuthorizationEntity>();

    public virtual ICollection<ContactAuthorizationEntity> ContactAuthorizationEntity { get; set; } = new List<ContactAuthorizationEntity>();

    public virtual ICollection<PersonaEntity> Persona { get; set; } = new List<PersonaEntity>();
}