// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authorization.Infrastructure.Entities;

public partial class Authorization
{
    public int ContactId { get; set; }

    public int AccountId { get; set; }

    public int ActionId { get; set; }

    public int? CreationDate { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual Action Action { get; set; }

    public virtual ContactEntity Contact { get; set; }
}