// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class ContactAuthorizationEntity
{
    public int ContactId { get; set; }

    public int AccountId { get; set; }

    public int AuthorizationId { get; set; }

    public DateTime CreationDate { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual AuthorizationEntity Authorization { get; set; }

    public virtual ContactEntity Contact { get; set; }
}