// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authorization.Infrastructure.Entities;

public partial class ContactEntity
{
    public int ContactId { get; set; }

    public Guid ContactGlobalUniqueId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ContactEmail { get; set; }

    public string PersonnaName { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Authorization> Authorization { get; set; } = new List<Authorization>();
}