// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class ContactEntity
{
    public int ContactId { get; set; }

    public Guid? ContactGlobalUniqueId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public string PersonaName { get; set; }

    public DateTime CreationDate { get; set; }

    public long IsActive { get; set; }

    public virtual ICollection<AuthorizationEntity> AuthorizationEntity { get; set; } = new List<AuthorizationEntity>();
}
