// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class CosmosDb
{
    public string Id { get; set; }

    public string AccountName { get; set; }

    public string AccountId { get; set; }

    public string ContactLoginName { get; set; }

    public string AssetId { get; set; }

    public string Code { get; set; }
}