// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authorization.Infrastructure.Entities;

public partial class Personna
{
    public int PersonnaId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Action> Action { get; set; } = new List<Action>();
}