// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class PersonnaEntity
{
    public int PersonnaId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public virtual ICollection<ActionEntity> Action { get; set; } = new List<ActionEntity>();
}