// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class PersonnaActionEntity
{
    public int PersonnaId { get; set; }

    public int ActionId { get; set; }

    public virtual ActionEntity Action { get; set; }

    public virtual PersonnaEntity Personna { get; set; }
}