// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class PersonaAuthorization
{
    public int PersonaId { get; set; }

    public int AuthorizationId { get; set; }

    public virtual AuthorizationEntity Authorization { get; set; }

    public virtual Persona Persona { get; set; }
}