// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class ResourceEntity
{
    public int ResourceId { get; set; }

    public int? ParentId { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public string Category { get; set; }

    public string Code { get; set; }

    public int? OrderShow { get; set; }

    public string Type { get; set; }

    public virtual ICollection<AccountResourceEntity> AccountResourceEntity { get; set; } = new List<AccountResourceEntity>();

    public virtual ICollection<ActionEntity> ActionEntity { get; set; } = new List<ActionEntity>();

    public virtual ICollection<ResourceEntity> InverseParent { get; set; } = new List<ResourceEntity>();

    public virtual ResourceEntity Parent { get; set; }
}