// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Authorization.Infrastructure.Entities;

public partial class ResourceEntity
{
    public int ResourceId { get; set; }

    public int? ParentId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public bool IsVisible { get; set; }

    public virtual ICollection<ResourceEntity> InverseParent { get; set; } = new List<ResourceEntity>();

    public virtual ResourceEntity Parent { get; set; }
}
