// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authorization.Infrastructure.Entities;

public partial class Resource
{
    public int ResourceId { get; set; }

    public int? ParentId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Url { get; set; }

    public bool? Visible { get; set; }

    public virtual ICollection<Resource> InverseParent { get; set; } = new List<Resource>();

    public virtual Resource Parent { get; set; }
}